from __future__ import annotations

from io import BytesIO

from typing import Union

from PIL import Image, ImageDraw, ImageFont


def _font(size: int, bold: bool = False) -> Union[ImageFont.FreeTypeFont, ImageFont.ImageFont]:
    candidates = [
        "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
    ]
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            continue
    return ImageFont.load_default()


def prediction_pdf(
    home_team: str,
    away_team: str,
    prediction: str,
    confidence: float,
    explanation: str,
    probabilities: dict[str, float],
) -> bytes:
    img = Image.new("RGB", (1240, 1754), "#08111f")
    draw = ImageDraw.Draw(img)
    draw.rectangle((0, 0, 1240, 260), fill="#111827")
    draw.rounded_rectangle((70, 86, 1170, 1660), radius=34, fill="#111a2e", outline="#2b3a67", width=3)
    draw.text((105, 110), "Sports Analytics Prediction Report", fill="#f8fbff", font=_font(44, True))
    draw.text((105, 178), f"{home_team} vs {away_team}", fill="#9ddcff", font=_font(30))
    draw.text((105, 310), "Predicted Outcome", fill="#a8b3cf", font=_font(24, True))
    draw.text((105, 350), prediction, fill="#ffffff", font=_font(58, True))
    draw.text((105, 430), f"Confidence Score: {confidence:.2f}%", fill="#c4b5fd", font=_font(28, True))

    y = 535
    draw.text((105, y), "Outcome Probabilities", fill="#a8b3cf", font=_font(24, True))
    y += 54
    for label, probability in probabilities.items():
        width = int(probability * 760)
        draw.text((130, y), f"{label}: {probability * 100:.2f}%", fill="#f8fbff", font=_font(24))
        draw.rounded_rectangle((420, y + 4, 420 + width, y + 30), radius=12, fill="#38bdf8")
        draw.rounded_rectangle((420, y + 4, 1180, y + 30), radius=12, outline="#334155", width=2)
        y += 58

    y += 36
    draw.text((105, y), "Model Explanation", fill="#a8b3cf", font=_font(24, True))
    y += 50
    words = explanation.replace("**", "").split()
    line = ""
    for word in words:
        test_line = f"{line} {word}".strip()
        if draw.textlength(test_line, font=_font(24)) > 980:
            draw.text((105, y), line, fill="#e5edff", font=_font(24))
            line = word
            y += 36
        else:
            line = test_line
    if line:
        draw.text((105, y), line, fill="#e5edff", font=_font(24))

    draw.text((105, 1570), "Generated by the Sports Analytics Dashboard capstone application.", fill="#94a3b8", font=_font(20))
    buffer = BytesIO()
    img.save(buffer, format="PDF", resolution=100.0)
    return buffer.getvalue()
